name: Testing django server

on:
  push:
  pull_request:
    branches: [ "master", 'backend' ]

jobs:
  build_and_test_backend:
    name: Run, build and test backend
    env:
      SECRET_KEY: django-insecure-n$e-qm6#6@du0=+^v0d%eeg84l6=g!o$4c%awh+yh0--gpx_h8
      POSTGRES_USER: POSTGRES_USER
      POSTGRES_PASSWORD: POSTGRES_PASSWORD
      POSTGRES_DB: POSTGRES_DB
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432
      REDIS_CELERY: localhost
      REDIS_CACHE: localhost
      DJANGO_SETTINGS_MODULE: concertify.settings
    runs-on: ubuntu-latest
    services:
      database:
        image: postgres:latest
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: POSTGRES_USER
          POSTGRES_PASSWORD: POSTGRES_PASSWORD
          POSTGRES_DB: POSTGRES_DB
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
      redis_cache:
        image: redis:latest
        ports:
          - 6379:6379
        options: --health-cmd "redis-cli ping" --health-interval 10s --health-timeout 5s --health-retries 5
      redis_celery:
        image: redis:latest
        ports:
          - 6380:6379
        options: --health-cmd "redis-cli ping" --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.10.12
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      working-directory: ./backend
    # - name: Test migrations
    #   run: |
    #     echo "||||||||||||||||||||||||||||||||||||||||||||||||||||||"
    #     echo $POSTGRES_HOST
    #     echo "||||||||||||||||||||||||||||||||||||||||||||||||||||||"
    #     python manage.py migrate --no-input
    #   working-directory: ./backend
    - name: Create test_fixture.json
      run: |
        python backend/fixtures/generate_fixtures.py --test
    - name: Run Django tests
      run: python manage.py test -v2
      working-directory: ./backend
      env:
        SECRET_KEY: django-insecure-n$e-qm6#6@du0=+^v0d%eeg84l6=g!o$4c%awh+yh0--gpx_h8
        POSTGRES_USER: POSTGRES_USER
        POSTGRES_PASSWORD: POSTGRES_PASSWORD
        POSTGRES_DB: POSTGRES_DB
        POSTGRES_HOST: localhost
        POSTGRES_PORT: 5432
        REDIS_CELERY: localhost
        REDIS_CACHE: localhost
        DJANGO_SETTINGS_MODULE: concertify.settings
  flake8:
    name: Flake8 Check
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.10.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: Run Flake8
        run: |
          flake8 . --exclude=*/migrations/*
        working-directory: ./backend
  
