name: Django CI

on:
  push:
    branches: [ "master", "backend" ]
  pull_request:
    branches: [ "master", "backend" ]

jobs:
  build:

    runs-on: ubuntu-latest
    container: python:latest

    env:
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
      POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
      POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
      DJANGO_SETTINGS_MODULE: ${{ secrets.DJANGO_SETTINGS_MODULE }}

    services:
      database:
        image: postgres:latest
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
      redis_cache:
        image: redis:latest
        ports:
          - 6379:6379
      redis_celery:
        image: redis:latest
        ports:
          - 6380:6379
    
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r backend/requirements.txt
        python backend/fixtures/generate_fixtures.py --test
        echo "asdasdaaaaaaaaaaaa"
        ls -l backend/fixtures
        chmod 777 backend/fixtures/test_fixture.json 
        python backend/manage.py test events
    - name: Tests
      run: python backend/manage.py test events
    - name: Run server
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        python manage.py migrate --no-input
        python manage.py runserver 0.0.0.0:8000 &
      working-directory: ./backend
    # - name: Run Tests
    #   run: |
    #     python manage.py test
    #   working-directory: ./backend
