name: Django CI

on:
  push:
    branches: [ "master", "backend" ]
  pull_request:
    branches: [ "master", "backend" ]

jobs:
  build:

    runs-on: ubuntu-latest
    container: python:latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r backend/requirements.txt
    - name: Run Tests
      run: |
        python backend/manage.py test
